- .github/workflows/deploy.yml
Signed-off-by: Upkar Lidder <upkar@pm.me>
> fixing variable and testing ci/cd again

- .github/workflows/deploy.yml
Signed-off-by: Upkar Lidder <upkar@pm.me>
> fixing container-name and testing ci/cd again

- .github/workflows/deploy.yml
Signed-off-by: Upkar Lidder <ulidder@us.ibm.com>
> adding auth and dashboard to ci/cd

- .github/workflows/deploy.yml
Signed-off-by: Upkar Lidder <upkar@pm.me>
> adding vcap-local.json to dev directory during ci/cd

- prometeo-dashboard/api-main/dashboard_manager.py
- prometeo-dashboard/package.json
- prometeo-dashboard/src/components/DeviceChart/index.js
- prometeo-dashboard/src/components/DeviceDashboardGaugeSet/index.js
- prometeo-dashboard/src/components/DeviceDetailsGaugeSet/index.js
- prometeo-dashboard/src/content/DashboardPage/_dashboard-page.scss
- prometeo-dashboard/src/content/DashboardPage/dashboardGrid.js
- prometeo-dashboard/src/hooks/useDashboard.js
- prometeo-dashboard/src/hooks/useDetails.js
- prometeo-dashboard/yarn.lock
- prototypes/charts.js
> Fix timezone parsing.

- prometeo-dashboard/src/components/DeviceDashboardGaugeSet/index.js
- prometeo-dashboard/src/components/DeviceDetailsGaugeSet/index.js
- prometeo-dashboard/src/content/DashboardPage/dashboardGrid.js
- prometeo-dashboard/src/locales/ca.json
- prometeo-dashboard/src/locales/en.json
- prometeo-dashboard/src/locales/es.json
> Add updated translations.

- prometeo-dashboard/src/components/DeviceDashboardGaugeSet/index.js
- prometeo-dashboard/src/components/DeviceDetailsGaugeSet/index.js
- prometeo-dashboard/src/hooks/useDashboard.js
> Add more spacing for text.

- .github/workflows/deploy.yml
- prometeo-dashboard/k8s/ingress-dryrun.yml
- removing ingress controller
- testing deployment to Prometeo cluster
> testing deployment

- README.md
Updating Prometeo wording to Pyrrah
Only concern is that the subdirectory might not be updated from 'prometeo-dashboard' to 'pyrrah-dashboard'.
> Update README.md - dashboard

- pyrrha-dashboard/yarn.lock
> Upgrade packages.

- pyrrha-dashboard/.gitignore
- pyrrha-dashboard/api-main/api.py
- pyrrha-dashboard/api-main/dashboard_manager.py
- pyrrha-dashboard/api-main/device_manager.py
- pyrrha-dashboard/api-main/event_manager.py
- pyrrha-dashboard/api-main/firefighter_manager.py
> Run formatter.

- pyrrha-dashboard/api-main/api.py
- pyrrha-dashboard/src/hooks/useDashboard.js
- pyrrha-dashboard/src/hooks/useDetails.js
> Handle empty set of devices.

- pyrrha-dashboard/.env
- pyrrha-dashboard/src/setupProxy.js
- pyrrha-dashboard/src/utils/Constants.js
@krook please review. I tested locally with remove ws and local ws values. Seems to work fine.
> extracting hard coded values for ws and proxy settings

- pyrrha-dashboard/src/components/DeviceGauge/index.js
> Change to one decimal place in the gauges.

- pyrrha-dashboard/api-main/__init__.py
- pyrrha-dashboard/api-main/api.py
- pyrrha-dashboard/api-main/dashboard_manager.py
- pyrrha-dashboard/api-main/device_manager.py
- pyrrha-dashboard/api-main/event_manager.py
- pyrrha-dashboard/api-main/firefighter_manager.py
- pyrrha-dashboard/api-main/requirements.txt
- pyrrha-dashboard/package.json
> Refactor Python database access, logging, and formatting.

- README.md
**Describe at a high level the solution you're providing**
Update to link to other components.
> Update to link to other components.

- pyrrha-dashboard/src/Router.js
- pyrrha-dashboard/src/content/DashboardPage/index.js
- pyrrha-dashboard/src/content/DetailsPage/index.js
- pyrrha-dashboard/src/content/DevicesPage/index.js
- pyrrha-dashboard/src/content/EventsPage/index.js
- pyrrha-dashboard/src/content/FirefightersPage/index.js
- pyrrha-dashboard/src/content/MapPage/index.js
- pyrrha-dashboard/src/content/ProfilePage/index.js
- pyrrha-dashboard/yarn.lock
**Describe at a high level the solution you're providing**
A clear and concise description of what you changed.
**Is this a patch, a minor version change, or a major version change**
Patch, minor, or major.
**Is this related to an open issue?**
No
**Additional context**
Add any other technical detail or considerations here.
> Move header component into Router

- pyrrha-dashboard/src/components/DeviceTable/headers.js
- pyrrha-dashboard/src/components/DeviceTable/index.js
- pyrrha-dashboard/src/content/MapPage/_map-page.scss
> Add color code to table rows.

- pyrrha-dashboard/api-auth/Dockerfile
Signed-off-by: Upkar Lidder <ulidder@us.ibm.com>
**Describe at a high level the solution you're providing**
fixing ubi permission error with node_modules
> fixing ubi permission error with node_modules

- .github/workflows/deploy-dev.yml
**Describe at a high level the solution you're providing**
Run dev deploy on every push to main
> Run dev deploy on every push to main

- pyrrha-dashboard/src/components/DeviceMap/index.js
> Experimenting with excluding mapbox-gl from babel transpiling
